### ISSUE TITLE
How can I use local OSM/Nominatim server?

### ISSUE THREAD

**Issue by asheetal** [jessecambon/tidygeocoder#21]
There is a fair usage policy on OSM.org. How can I use local local OSM installation?

**Comment by jessecambon** [comment]
This isn't possible in the version currently on CRAN, unfortunately. However, I am working on a new version which will allow you to input a custom API URL so that you could use a local OSM installation. I haven't implemented this feature just yet, but I can let you know when I do so that you can test it out.

**Comment by jessecambon** [comment]
@asheetal I have a branch ready for you if you want to test it. You can use the `api_url` parameter from either the `geocode` or `geo` functions to set your own API URL. The geocode function takes a dataframe input while the geo function takes address inputs as vectors. You can install with this command: 

```r
devtools::install_github("jessecambon/tidygeocoder", ref = 'dev')
```
