### ISSUE TITLE
Support for Google Maps?

### ISSUE THREAD

**Issue by stevenprimeaux** [jessecambon/tidygeocoder#34]
Are there plans in the works to add support for Google Maps? The ggmap package could provide a model for those wrappers.

**Comment by jessecambon** [comment]
I'm open to adding the Google geocoder in the future, but I'm not currently working on it. If anyone is up for taking this on, here are some general instructions on how support for a geocoder service can be added to the package.

1. Update the [api_parameter_reference](https://jessecambon.github.io/tidygeocoder/articles/tidygeocoder.html#api-reference) dataset to include the geocoder service. Each service is referred to by a short name in the `method` field (which is how the service is specified in the `geo()` and `geocode()` functions). The `api_name` field should reflect the specific parameter names of the geocoder service.
2. Update the [`extract_results()` function](https://github.com/jessecambon/tidygeocoder/blob/master/R/utils.R) which is used for parsing single addresses (ie. not batch geocoding). You can see examples of how I've tested out parsing the results of geocoder services [here](https://github.com/jessecambon/tidygeocoder/tree/master/sandbox/query_debugging).
3. If the service supports batch geocoding, add a function for this capability to [R/batch_geocoding.R](https://github.com/jessecambon/tidygeocoder/blob/master/R/batch_geocoding.R). These functions are called from `geo()`.
4. If the service requires an API key, update the [`get_key()` function](https://github.com/jessecambon/tidygeocoder/blob/master/R/query_factory.R) which loads the API key from an environmental variable.
5. Add a function for obtaining the API URL to [R/query_factory.R](https://github.com/jessecambon/tidygeocoder/blob/master/R/query_factory.R). 
6. Make relevant updates to the [geo() function](https://github.com/jessecambon/tidygeocoder/blob/master/R/geo.R). In particular look at the if clauses that reference the `method` (ie. usage limits are specifically applied to the "osm" and "iq" methods). Also, if batch geocoding is supported then the call to the new batch geocoding function will need to be added.
7. Add a new `geo_<method>()` conveniance function to [R/geo_methods.R](https://github.com/jessecambon/tidygeocoder/blob/master/R/geo_methods.R).

Happy to provide additional guidance and give credit for code contributions in the DESCRIPTION file.

**Comment by chris31415926535** [comment]
I might be able to help here: I've written a tidy interface to Google's geocoder service to help with some not-for-profit work (you can [see the source code here](https://github.com/Ottawa-Neighbourhood-Study/onsr/blob/master/R/geocoding.R), or [install the dev package here](https://github.com/Ottawa-Neighbourhood-Study/onsr) ). 

Of course I did it in my own idiosyncratic way, so over the next while I'll look and see how much work it would be to bring it into the tidygeocoder framework.

**Comment by chris31415926535** [comment]
I've got a basic implementation working locally. I like your approach and I've learned a few things.

**Question:** are the parameters `city`, `street`, `country`, etc. always passed as individual elements of API queries, or is there a function (that I'm missing) that ever collapses them into a single string?

I ask because (from my read of [the docs](https://developers.google.com/maps/documentation/geocoding/overview)) Google accepts four main parameters: a mandatory single `address` and `api_key`, with optional `language` and `region`. But then my new entry in api_reference.R is only four lines long, which looks empty compared to the others :)

**Comment by jessecambon** [comment]
@chris31415926535  Thanks for submitting the PR. I haven't had a chance to review it in detail yet, but it looks good from skimming through it. 

Also, it looks like you figured out the answer to your question already, but the `address` field is the one to use for the combined address while the other arguments like `street` and `city` are for breaking the address out into components. This reminds me that I should revisit the idea of throwing the user an error if they use an argument that is not compatible with the service that they have chosen (ie. using the `street` argument with the Google geocoder).

**Comment by jessecambon** [comment]
@chris31415926535 I've pulled in your PR to the [google-geocoder branch](https://github.com/jessecambon/tidygeocoder/tree/google-geocoder). Good work on this - it worked well for me in the testing I did. One addition I made was to extract error messages from the google geocoder so that they can be displayed to the user (#54). 

I also added your name to the DESCRIPTION file as a package author. Feel free to add an email address if you would like (or email/message it to me and I can add it). I'll plan on looking at addressing #53, doing some more testing, and pushing this up to the master branch so it will be included in the next CRAN release.

**Comment by chris31415926535** [comment]
@jessecambon Thanks for the kind words, and I'm glad I could help! If you don't mind, I'm still getting the hang of git so it's probably easier for you to add my email address: christopher.a.belanger@gmail.com

**Comment by jessecambon** [comment]
@chris31415926535 You're welcome, I added your email to the DESCRIPTION file. Also, your code is now in the master branch along with a few other enhancements and bug fixes I'm looking to roll out for the next CRAN release. Feel free to test it out:

```r
devtools::install_github("jessecambon/tidygeocoder")
```

**Comment by chris31415926535** [comment]
@jessecambon I installed the GitHub version to test it out and it works like a charm. And good call on parsing the Google-specific errors.
