### ISSUE TITLE
Error: All nested columns must have the same number of elements.

### ISSUE THREAD

**Issue by durraniu** [jessecambon/tidygeocoder#4]
Thank you for this package. It looks super easy and very cool.   

# Data
My data set has following address column:
```
df <- sdata %>% 
  mutate(address = paste0(city, ", ", province_state, ", ", country)) 

> df %>% select(address)
# A tibble: 23 x 1
   address                          
   <chr>                            
 1 Ahmedabad, Gujarat, India        
 2 Bengaluru, Karnataka, India      
 3 Mumbai, Maharashtra, India       
 4 Ashoknagar, Madhya pradesh, India
 5 Ahmedabad, Gujarat, India        
 6 Vijayawada, Andhra Pradesh, India
 7 New Delhi, Delhi, India          
 8 Hyderabad, Telangana, India      
 9 Khambhat, Gujarat, India         
10 Amritsar, punjab, India          
# … with 13 more rows
```

# Code
I am using the following code to do the geocoding:
`df <- df  %>%
 geocode(address, method = "osm")`  

## Error:
`No results found for "Khajoori khas, New Delhi, India".Error: All nested columns must have the same number of elements.`  

1. Is there a way to skip the result where a warning is generated?    
2. Regardless of the above warning, what does this error mean?

**Comment by jessecambon** [comment]
Thanks, it looks like that address is not being found by the Nominatim geocoder service. For reference, you can check which addresses return results directly here: https://nominatim.openstreetmap.org/search.php?q=Khajoori+khas%2C+New+Delhi%2C+India&polygon_geojson=1&viewbox=

As for the error, I attempted to reproduce it with a minimal example below but I just got a warning instead of an error.

```
df <- tibble(addr=c('Khajoori khas, New Delhi, India',"Bengaluru, Karnataka, India"))
df %>% geocode(addr,method='osm')

# A tibble: 2 x 3
  addr                              lat  long
  <chr>                           <dbl> <dbl>
1 Khajoori khas, New Delhi, India  NA    NA  
2 Bengaluru, Karnataka, India      13.0  77.6
Warning message:
In FUN(X[[i]], ...) :
  No results found for "Khajoori khas, New Delhi, India".
```

Your error seems to be coming from `tidyr::unest` which I use in the `geocode` function: https://github.com/tidyverse/tidyr/issues/460. You might try updating `tidyr` and/or make sure there aren't any nesting issues in your dataset to see if that resolves the problem. If you have a full reproducible example then I can take a look and try to debug.

**Comment by durraniu** [comment]
Thank you. Updating the `tidyr` package to version 1.0.0 fixed the error.
