### ISSUE TITLE
Pad fips with 0's for `geocode()`

### ISSUE THREAD

**Issue by atungate** [jessecambon/tidygeocoder#47]
Fantastic package! One thing for you to consider is to pad the fips from `geocode(...,  method = 'census', full_results = TRUE, return_type = "geographies")` with `0`'s on the left to be consistent with the number of digits expected (outlined by the census: https://www.census.gov/programs-surveys/geography/guidance/geo-identifiers.html#par_textimage_8). Of course, you'll also have to force those columns to be character because of the leading zeros. For example, changing this:

```
library(dplyr)
library(tidygeocoder)

address_single <- tibble(singlelineaddress = c('11 Wall St, NY, NY', 
                                               '600 Peachtree Street NE, Atlanta, Georgia'))
address_components <- tribble(
  ~street                      , ~cty,               ~st,
  '11 Wall St',                  'NY',               'NY',
  '600 Peachtree Street NE',     'Atlanta',          'GA'
)

address_single %>% geocode(address = singlelineaddress, method = 'census',
                           full_results = TRUE, return_type = "geographies") %>%
  select(matches("(fips|tract|block)$"))
# A tibble: 2 x 4
  state_fips county_fips census_tract census_block
       <int>       <int>        <int>        <int>
1         36          61          700         1008
2         13         121         1900         2003
```

To this:
```
address_single %>% geocode(address = singlelineaddress, method = 'census',
                           full_results = TRUE, return_type = "geographies") %>%
  transmute(state_fips = stringr::str_pad(state_fips, 2, pad = "0"),
            county_fips = stringr::str_pad(county_fips, 3, pad = "0"),
            census_tract = stringr::str_pad(census_tract, 6, pad = "0"),
            census_block = stringr::str_pad(census_block, 4, pad = "0"))
# A tibble: 2 x 4
  state_fips county_fips census_tract census_block
  <chr>      <chr>       <chr>        <chr>       
1 36         061         000700       1008        
2 13         121         001900       2003 
```
If it would help I can submit a PR, I just need to dig into the code more to figure out if you can retain the 0's upstream or if you'll need to do it similar to how I did it (but avoiding the `stringr` import).

**Comment by jessecambon** [comment]
@atungate thanks for this, I agree this would be a good enhancement. I would just want to make sure that it's done in a way where it doesn't interfere with other columns of the same name (ie. "census_block" etc.) that might already exist in an input dataset (ie. not coming from the geocoding service results). Also, as you note having the solution in base R so that we don't have to add a dependency would be good.

In [line 294 of geo.R](https://github.com/jessecambon/tidygeocoder/blob/master/R/geo.R#L294) there is a call to the `extract_results()` function which is in [utils.R](https://github.com/jessecambon/tidygeocoder/blob/master/R/utils.R#L52). I think we could probably add an if statement to `extract_results()` to implement this solution (ie. `if method == 'census' & full_results == TRUE`). I'll have somewhat limited time for development in the near future, but you're welcome to take a stab at it and submit a PR.

**Comment by atungate** [comment]
@jessecambon, sounds good and thanks for the head-start! I will take a look at things and submit a PR in the next week or two--then you can decide from there!

**Comment by jessecambon** [comment]
@atungate I've got a fix for this in the master branch now if you want to test it out. The `state_fips` , `county_fips`, `census_tract`, and `census_block` fields are now read in as character (instead of numeric) so the leading zeros are preserved (when using the Census batch geocoder). 

```r
a <- sample_addresses %>% head(3) %>% geocode(addr, full_results = TRUE, return_type = 'geographies')
View(a)
```

![image](https://user-images.githubusercontent.com/31526206/102828924-e5e30700-43b3-11eb-992d-50de5b50f498.png)

**Comment by atungate** [comment]
Hey @jessecambon, works great for me! Thank you! I took a crack at fixing it upstream but couldn't figure it out. I was going to come back to it and use `sprintf()` in-place of `str_pad()`but I am glad you figured out a better solution (than the one I was going to try). Great work!
