### ISSUE TITLE
Add TomTom support

### ISSUE THREAD

**Issue by dieghernan** [jessecambon/tidygeocoder#76]
Following #62 , I have implemented TomTom:

- Docs: 
  - Geocode: https://developer.tomtom.com/search-api/search-api-documentation-geocoding/geocode
  - Reverse Geocode: https://developer.tomtom.com/search-api/search-api-documentation-reverse-geocoding/reverse-geocode
  - Batch: https://developer.tomtom.com/search-api/search-api-documentation-batch-search/asynchronous-batch-submission

See the checklist below:

<details>

## Data
- [x]  `data-raw/api_reference.R` updated
- [x]  Modify `R/data.R`

## Sandbox
- [x]  Added `sandbox/query_debugging/tomtom_test.R `
- [x]  Added `sandbox/reverse_queries/tomtom_reverse.R`
- [x] Sandbox for TomTom batch added
- [x] Sandbox for TomTom batch reverse added

## Code
- [x]  `R/utils.R` - Utils added for TomTom
- [x]  `R/query_factory.R` updated
- [x]  `R/geo_methods.R` updated
- [x]  `R/geo.R` updated
- [x]  `R/reverse_geo.R` updated

## Batch
- [x]  `R/batch_geocoding.R ` updated
- [x]  `R/reverse_batch_geocoding.R` updated

## Testing
- [x]  `testthat` test added
- [x]  Modify `regression_testing.Rmd`
- [x]  Run tests included in <https://github.com/jessecambon/tidygeocoder/blob/master/cran-comments.md>

## Misc
- [x] Update README
- [x]  Fix on `R/reverse_geo.R` to avoid errors on `no_query = TRUE`

</details>

I am polishing the PR with a final huge batch geocoding test, but overall **my experience on this is that TomTom runs smoothly and fast**, I think it could be a great addition to the package

**Comment by jessecambon** [comment]
@dieghernan  I pulled this into master. :+1:  Note that I changed the [query_api](https://jessecambon.github.io/tidygeocoder/reference/query_api.html) function to return a named list so that we can see the HTTP response status code. I also adjusted the logic in geo(), reverse_geo(), and related tests to use the HTTP status code when checking if a query was successful.

**Comment by dieghernan** [comment]
Agree, the json parsing inside `query_api` was a bit troublesome, I think it is better now

**Comment by dieghernan** [comment]
I think the error handling of TomTom is not incorporated after the last PR:

https://github.com/dieghernan/tidygeocoder/blob/54ae775a8783006d6373450d73210e3547d8de66/R/utils.R#L196:L198

**Comment by jessecambon** [comment]
@dieghernan I changed the extract_errors_from_results() function in utils.R so that it will just display the raw content if it is not valid JSON:

https://github.com/jessecambon/tidygeocoder/blob/739853f135df1955f74e929ebafaf6f9e840b96a/R/utils.R#L155

That worked for me with TomTom when I passed an invalid api key, but let me know if you spot any issues. That function will only be called if the HTTP response status != 200.

**Comment by dieghernan** [comment]
Thanks!! I’ll check and would let you know
